In [2]:
def gaussian_kernel0(distances):
    weights=np.exp(-0*(distances)**2)
    return weights/np.sum(weights)
def gaussian_kernel1(distances):
    weights=np.exp(-1*(distances)**2)
    return weights/np.sum(weights)
def gaussian_kernel5(distances):
    weights=np.exp(-5*(distances)**2)
    return weights/np.sum(weights)
def gaussian_kernell0(distances):
    weights=np.exp(-10*(distances)**2)
    return weights/np.sum(weights)
def gaussian_kernel25(distances):
    weights=np.exp(-25*(distances)**2)
    return weights/np.sum(weights)


#id:23-115-69 
import numpy as np
import pandas as pd

#read in csv data
df = pd.read_csv('week6.csv', comment="#")
#print(df.head())

#dummy data
d_X = [-1, 0, 1]
d_X = np.array(d_X)
d_X=d_X.reshape(-1, 1)
d_y = [0, 1, 0]
grid = np.linspace(-3, 3)
grid=grid.reshape(-1, 1)
#Using kNN and kernalised ridge regression generate predictions on the grid
import matplotlib.pyplot as plt
#kNN
from sklearn import neighbors, preprocessing
from sklearn.model_selection import train_test_split
knn0=neighbors.KNeighborsRegressor(n_neighbors=3, weights=gaussian_kernel0).fit(d_X, d_y)
knn1=neighbors.KNeighborsRegressor(n_neighbors=3, weights=gaussian_kernel1).fit(d_X, d_y)
knn5=neighbors.KNeighborsRegressor(n_neighbors=3, weights=gaussian_kernel5).fit(d_X, d_y)
knn10=neighbors.KNeighborsRegressor(n_neighbors=3, weights=gaussian_kernell0).fit(d_X, d_y)
knn25=neighbors.KNeighborsRegressor(n_neighbors=3, weights=gaussian_kernel25).fit(d_X, d_y)

#plotting our results
%matplotlib widget
plt.figure()
preds=knn0.predict(grid)
plt.plot(grid, preds, label='gamma=0', color='y')
preds=knn1.predict(grid)
plt.plot(grid, preds, label='gamma=1', color='r')
preds=knn5.predict(grid)
plt.plot(grid, preds, label='gamma=5', color='g')
preds=knn10.predict(grid)
plt.plot(grid, preds, label='gamma=10', color='purple')
preds=knn25.predict(grid)
plt.plot(grid, preds, label='gamma=25', color='b')
plt.legend()
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [15]:
#KernelRidge
from sklearn.kernel_ridge import KernelRidge

C_range = [0.1, 1, 1000]
gamma_range = [0, 1, 5, 10, 25]
coefficients=[]

for gam in gamma_range:
    plt.figure()
    plt.title('gamma = %d'%gam)
    plt.xlabel('X')
    plt.ylabel('y')
    
    temp=[]
    
    for C in C_range:
        KRidge = KernelRidge(alpha=1/(2*C), kernel='rbf', gamma=gam)
        KRidge.fit(d_X, d_y)
        preds=KRidge.predict(grid)
        plt.plot(grid, preds, label = ' C=%d'%C)
        temp.append(KRidge.dual_coef_)
        
    plt.legend()
    plt.show()
    
    temp=np.array(temp)
    coefficients.append(temp)
coefficients=np.array(coefficients)
print(coefficients)


C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  if __name__ == '__main__':


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  if __name__ == '__main__':


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  if __name__ == '__main__':


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  if __name__ == '__main__':


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  if __name__ == '__main__':


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[[[-2.50000000e-02  1.75000000e-01 -2.50000000e-02]
  [-5.71428571e-01  1.42857143e+00 -5.71428571e-01]
  [-6.66555574e+02  1.33344443e+03 -6.66555574e+02]]

 [[-1.02647158e-02  1.67925393e-01 -1.02647158e-02]
  [-1.83316181e-01  7.56584339e-01 -1.83316181e-01]
  [-4.91387484e-01  1.36086227e+00 -4.91387484e-01]]

 [[-1.87165666e-04  1.66667087e-01 -1.87165666e-04]
  [-2.99476396e-03  6.66693571e-01 -2.99476396e-03]
  [-6.73182473e-03  9.99590922e-01 -6.73182473e-03]]

 [[-1.26110916e-06  1.66666667e-01 -1.26110916e-06]
  [-2.01777466e-05  6.66666668e-01 -2.01777466e-05]
  [-4.53545640e-05  9.99500254e-01 -4.53545640e-05]]

 [[-3.85776218e-13  1.66666667e-01 -3.85776218e-13]
  [-6.17241950e-12  6.66666667e-01 -6.17241950e-12]
  [-1.38740663e-11  9.99500250e-01 -1.38740663e-11]]]
